### ISSUE TITLE
IGMPv3: When sending an IGMPv3 query pico does not send a membership report.

### ISSUE THREAD

**Issue by TassThomas** [tass-belgium/picotcp#181]
When pico is subscribed to a multicast stream and an IGMPv3 general/group specific query is sent to it, there is no response
A membership response indicating to which multicast stream the DUT is subscribed is expected.

reproduce:
sudo ./run.sh --test igmpv3_send_query testcases/hardware/igmpv3_bench_dut.txt

**Comment by danielinux** [comment]
@SimonMaes ??

**Comment by SimonMaes** [comment]
@danielinux I've send you status-update via mail.

**Comment by danielinux** [comment]
Thanks!

**Comment by danielinux** [comment]
Test can be reproduced using any interface. On a Linux box, you can use the following code to generate an IGMPv3 global query:
```
#include <sys/socket.h>
#include <netinet/in.h>
#include <stdint.h>
#include <unistd.h>
#include <stdio.h>
#include <arpa/inet.h>


struct __attribute__((packed)) igmp3 {
    uint8_t type;
    uint8_t max_resp;
    uint16_t crc;
    uint32_t grp;
    uint32_t z0;
    uint32_t z1;
};


int main(void) {
    int s = socket(AF_INET, SOCK_RAW, IPPROTO_IGMP);
    struct igmp3 ig = {};
    struct sockaddr_in dst;
    dst.sin_family = AF_INET;
    dst.sin_addr.s_addr = inet_addr("10.50.0.5");
    ig.type = 0x11;
    ig.crc = 0xffee;

    if (s < 0) {
        perror("socket");
        return 1;
    }
    sendto(s, &ig, sizeof(ig), 0, (struct sockaddr *)&dst, sizeof(struct sockaddr_in));
}
```

**Comment by danielinux** [comment]
Waiting for QA confirmation (RF_Test new results)

**Comment by danielinux** [comment]
Thanks for the feeback, QA.
