### ISSUE TITLE
[IPv6] Fix ping6 for global addreses

### ISSUE THREAD

**Issue by mms1973** [tass-belgium/picotcp#190]
If we ping6 from a local-link address to a global address in the target, we receive a reply from local-link to local-link.

Could be a failure of ND discovery. At the moment the global address is hardcoded, so there must be also a way to configure it dynamically via serial, for instance

**Comment by S4mw1s3** [comment]
It's been a while now. I guess this one can be closed?

**Comment by danielinux** [comment]
Any input from @asselj @mms1973 ?

**Comment by danielinux** [comment]
Test cannot be tracked/reproduced. Closing.
