### ISSUE TITLE
TFTP: as per barebox community request, add support for RFC 2349

### ISSUE THREAD

**Issue by dpmik** [tass-belgium/picotcp#192]
API will be slightly changed.

**Comment by S4mw1s3** [comment]
I'm suspecting a typo here. RFC 2359 is about IMAP4 UIDPLUS extension and is obsoleted...
I think the request from the barebox community is for RFC 2349 which is about TFTP Timeout Interval and Transfer Size Options.

**Comment by dpmik** [comment]
In data mercoledì 7 gennaio 2015 02:13:18, Sam Van Den Berge ha 
scritto:
> I'm suspecting a typo here. RFC 2359 is about IMAP4 UIDPLUS 
extension and is
> obsoleted... I think the request from the barebox community is for RFC 
2349
> which is about TFTP Timeout Interval and Transfer Size Options.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/tass-belgium/picotcp/issues/192#issuecomment-69002258
You have right, the proper RFC is 2349.-- 
*Michele Di Pede*
Software Designer
Intelligent System / Altran

Gaston Geenslaan 9
3001 Leuven
Belgium
Tel: +32 (0)16 24 16 80
Mobile: +32 (0) 484 386 673
E-mail: michele.dipede@altran.com

intelligent-systems.altran.com

**Comment by dpmik** [comment]
Implemented in commit #4948eb8520
