### ISSUE TITLE
[mDNS] Implement DNS-SD

### ISSUE THREAD

**Issue by danielinux** [tass-belgium/picotcp#194]
Implement DNS-Service discovery in a picotcp module based on https://tools.ietf.org/html/rfc6763

**Comment by danielinux** [comment]
@TASSDevon  could it be we implemented the discovery but we don't currently have an API to advertise services running on the target (i.e. we wrote the "desktop"/"handheld" side of SD rather than the service device)?
Also, could you explain the relationship between mDNS and DNS-SD in terms of modules separation? I think we should design the modules in a way that DNS-SD is independent from mDNS, and can also be used (in the future) with unicast DNS, as specified by RFC6763.

I am assigning this to @thomasVE to shed some light on the current status.
Please update this thread with all the information needed to continue the development of this feature.

**Comment by thomasVE** [comment]
From this week on a professional bachelor student started his thesis/final project on this topic.
He will first get himself known with mdns and rfc6762 and rfc6763.
You can follow his journal on: https://github.com/jelledevleeschouwer/log/blob/master/README.md
