### ISSUE TITLE
[mDNS] check for RFC compliance, fix violations

### ISSUE THREAD

**Issue by danielinux** [tass-belgium/picotcp#195]
current mDNS implementation seems not to respect caching requirements for discovered peers in the network. 

- Add a cache of entries as specified in RFC6762 http://tools.ietf.org/html/rfc6762
- Check for other RFC violations and fix them

**Comment by jelledevleeschouwer** [comment]
As part of the development of the DNS-SD module I worked on the mDNS module as well. I think I've finished it as far as the RFC prescribes and I can move on to DNS-SD itself, which includes adding TXT and SRV records. I've written unit tests for the mDNS module and the common DNS code. As far as I know, no other functionalities should be implemented.

Funtionalities implemented:
* Claiming of multiple unique records
* Claiming of multiple shared records
* Claiming of the 2 above in a single API-function call
* API-call to set the hostname
* Unicast request questions (QU-questions)
* Answering via unicast
* Defending of unique records
* Conflict resolution mechanism
* Simultaneous Probe Tiebreaking
* Known Answer Suppression
* Caching of records with continuous updating
* DNS name compression and decompression
* Duplicate query suppression
* Priority of shared records over unique records
* Handling multiple answers
