### ISSUE TITLE
[MLD] Implement MLD and IPv6 Multicast sockets [RFC3810, RFC4604]

### ISSUE THREAD

**Issue by danielinux** [tass-belgium/picotcp#199]
1- Implement MLD as a separate module, using a similar interface as IGMP3
2- Make stack/pico_socket_multicast.c IPv6 compliant, using the same API as for IPv4, but replacing version-specific objects (addresses, links) with a generic one that can handle IPv6

**Comment by danielinux** [comment]
Hello @S4mw1s3 . Are you able to provide an estimation for this?

**Comment by S4mw1s3** [comment]
I forgot about this issue. I'm currently already assigned on another project so it will be at least end of march before I can start working on this. In the meantime I removed my assignment.

**Comment by danielinux** [comment]
@roel0 can you provide a status update?

**Comment by roel0** [comment]
pico_socket_multicast.c : 80%
pico_ipv6.c 60-70%
pico_mld.c : 0-10%

the multicast part should be able to be committed to dev branch before the weekend

**Comment by roel0** [comment]
Status update:

Unit testing!

pico_ipv6.c/pico_socket_multicast : Tested! However, stresstest still fails
pico_mld.c : Will write unit test tonight
functional test: hopefully this week

(Branch also urgently needs an update)

**Comment by roel0** [comment]
Functional test "freezes" on UDP test, still looking for the reason

**Comment by danielinux** [comment]
Closed via pull request #306
