### ISSUE TITLE
Pico accepts IP packets sent to host on different network

### ISSUE THREAD

**Issue by TassThomas** [tass-belgium/picotcp#207]
When sending an IP message to pico with wrong destination IP address but correct MAC address of the board pico is accepting the message and not discarding it. 

note: Pico DOES discard packages that have an ip address with the same network and subnet number. When one of those (or both) is different, pico IS accepting the packet.

reproduce:
sudo ./run.sh --test ip_check_address testcases/hardware/ipv4_bench_dut.txt

**Comment by danielinux** [comment]
Can't reproduce. @TassThomas please double check the test.

**Comment by TassThomas** [comment]
Testcase was fixed. Also added a new testcase to test this functionality, where just the host number of the ip address is different than the DUT ip's.
