### ISSUE TITLE
DHCP server still leaky

### ISSUE THREAD

**Issue by azuliani** [tass-belgium/picotcp#211]
... albeit in a much less trivial way this time. The amount lost is also smaller than in #210 , though still relevant.

Two valgrind logs are attached (below, for readability) for the memory footprint after 5 DHCP requests and 10 DHCP requests. It can be seen that some nodes in certain trees — which are still reachable — are never cleared. There is no mechanism to remove stale entries (e.g. from unfinished handshakes). 

There is one obvious way to fix this: add some sort of timeout to wipe old entries, but it is my opinion that this is not sufficient, since such an approach in an embedded context leaves devices strongly vulnerable to DoS attacks. An attacker could easily initiate many handshakes that never finish and crash a device in seconds.

Moreover, the DHCP transactions for the logs below _did_ finish, but still leak. I see no references to pico_tree_delete(), but plenty of calls to pico_tree_insert(), so it would appear the original author didn't care.

In conclusion: 
- Measures need to be taken to remove (stale) entries
- A limit must be imposed on the amount of unfinished transactions

I'm not sure how to proceed (hence the "question" tag),
Please discuss.

Valgrind output after 5 requests.
```
640 bytes in 20 blocks are still reachable in loss record 31 of 33
   at 0x4C2C080: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x401438: pico_dhcp_server_add_negotiation (pico_dhcp_server.c:203)
   by 0x401A7D: pico_dhcp_server_recv (pico_dhcp_server.c:355)
   by 0x401B43: pico_dhcpd_wakeup (pico_dhcp_server.c:378)
   by 0x40BAD5: pico_socket_udp_deliver_ipv4_mcast (pico_socket_udp.c:71)
   by 0x40BBD7: pico_socket_udp_deliver_ipv4 (pico_socket_udp.c:108)
   by 0x40BC95: pico_socket_udp_deliver (pico_socket_udp.c:190)
   by 0x404F0F: pico_socket_transport_deliver (pico_socket.c:526)
   by 0x404FB0: pico_socket_deliver (pico_socket.c:547)
   by 0x406A26: pico_transport_process_in (pico_socket.c:1782)
   by 0x413911: proto_loop_in (pico_protocol.c:60)
   by 0x4139B4: proto_loop (pico_protocol.c:86)

800 bytes in 20 blocks are still reachable in loss record 32 of 33
   at 0x4C2C080: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x4098F4: create_node (pico_tree.c:406)
   by 0x4091EF: pico_tree_insert_implementation (pico_tree.c:145)
   by 0x409145: pico_tree_insert (pico_tree.c:125)
   by 0x40150F: pico_dhcp_server_add_negotiation (pico_dhcp_server.c:223)
   by 0x401A7D: pico_dhcp_server_recv (pico_dhcp_server.c:355)
   by 0x401B43: pico_dhcpd_wakeup (pico_dhcp_server.c:378)
   by 0x40BAD5: pico_socket_udp_deliver_ipv4_mcast (pico_socket_udp.c:71)
   by 0x40BBD7: pico_socket_udp_deliver_ipv4 (pico_socket_udp.c:108)
   by 0x40BC95: pico_socket_udp_deliver (pico_socket_udp.c:190)
   by 0x404F0F: pico_socket_transport_deliver (pico_socket.c:526)
   by 0x404FB0: pico_socket_deliver (pico_socket.c:547)

LEAK SUMMARY:
   definitely lost: 0 bytes in 0 blocks
   indirectly lost: 0 bytes in 0 blocks
     possibly lost: 0 bytes in 0 blocks
   still reachable: 140,284 bytes in 94 blocks
        suppressed: 0 bytes in 0 blocks
```

Logs after 10 requests:
```
1,248 bytes in 39 blocks are still reachable in loss record 26 of 28
   at 0x4C2C080: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x401438: pico_dhcp_server_add_negotiation (pico_dhcp_server.c:203)
   by 0x401A7D: pico_dhcp_server_recv (pico_dhcp_server.c:355)
   by 0x401B43: pico_dhcpd_wakeup (pico_dhcp_server.c:378)
   by 0x40BAD5: pico_socket_udp_deliver_ipv4_mcast (pico_socket_udp.c:71)
   by 0x40BBD7: pico_socket_udp_deliver_ipv4 (pico_socket_udp.c:108)
   by 0x40BC95: pico_socket_udp_deliver (pico_socket_udp.c:190)
   by 0x404F0F: pico_socket_transport_deliver (pico_socket.c:526)
   by 0x404FB0: pico_socket_deliver (pico_socket.c:547)
   by 0x406A26: pico_transport_process_in (pico_socket.c:1782)
   by 0x413911: proto_loop_in (pico_protocol.c:60)
   by 0x4139B4: proto_loop (pico_protocol.c:86)

1,560 bytes in 39 blocks are still reachable in loss record 27 of 28
   at 0x4C2C080: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x4098F4: create_node (pico_tree.c:406)
   by 0x4091EF: pico_tree_insert_implementation (pico_tree.c:145)
   by 0x409145: pico_tree_insert (pico_tree.c:125)
   by 0x40150F: pico_dhcp_server_add_negotiation (pico_dhcp_server.c:223)
   by 0x401A7D: pico_dhcp_server_recv (pico_dhcp_server.c:355)
   by 0x401B43: pico_dhcpd_wakeup (pico_dhcp_server.c:378)
   by 0x40BAD5: pico_socket_udp_deliver_ipv4_mcast (pico_socket_udp.c:71)
   by 0x40BBD7: pico_socket_udp_deliver_ipv4 (pico_socket_udp.c:108)
   by 0x40BC95: pico_socket_udp_deliver (pico_socket_udp.c:190)
   by 0x404F0F: pico_socket_transport_deliver (pico_socket.c:526)
   by 0x404FB0: pico_socket_deliver (pico_socket.c:547)

LEAK SUMMARY:
   definitely lost: 0 bytes in 0 blocks
   indirectly lost: 0 bytes in 0 blocks
     possibly lost: 0 bytes in 0 blocks
   still reachable: 141,516 bytes in 128 blocks
        suppressed: 0 bytes in 0 blocks
```

P.S.: Don't let the huge 100k+ "still reachable" scare you. 95% of that is a huge sandbox-related block.

**Comment by marjantass** [comment]
There is a leak 36 bytes which is due to initializing the DHCP-server and not destroying it in the test plan. Except the former leakage I could not be able see the issue in the following scenarios:
1- In the complete flow while using also picotcp as DHCP-client and assigning IP addresses and sending an ACKfrom the server; this is repeated by several clients.
2- Using Scapy (a packet generator) for only sending DHCPDISCOVER and receiving an offer. This is repeated several times with Random MAC addresses. However there is no more leakage than the 36 bytes of the initialization.
Any idea about how to reproduce the issue.

**Comment by azuliani** [comment]
It's important to note that the leaked data is still reachable. As a result valgrind does not mark these sections as "definitely lost".

To reproduce, make sure valgrind is run with "--show-leak-kinds=all"  and "--leak-check=full"

**Comment by danielinux** [comment]
If the records are still reachable, could it be the normal behavior of the DHCP server, keeping track of the leases for the next requests?

**Comment by danielinux** [comment]
Does not seem to impact memory usage anyway. Considering for closing (wontfix/invalid).

Any more input @marjantass @azuliani ?
