### ISSUE TITLE
RFC4944: Implement LoWPAN Adaptation Layer

### ISSUE THREAD

**Issue by danielinux** [tass-belgium/picotcp#215]
Follow indications in RFC4944 for LoWPAN Adaptation Layer and Frame Format in section 5.
Adaptation layer should:
- support any device driver
- support loWPAN 16-bit and 64-bit L2 addresses
- support IPv4 transparent forwarding over loWPAN via NALP messages (using IPv4 fragmentation mechanisms)
- support IPv6 compression and addresses translations as described in RFC4944 section 5, 7, 8, 9
- support header compression mechanisms as specified in section 10 and updated in RFC6282, including IPv6 header compression and UDP header compression.

**Comment by phalox** [comment]
Just wondering what our policy is concerning closing issues?
* Tested?
* Integrated in master branch?
