### ISSUE TITLE
[TCP] socket is not closed after receiving RST-ACK

### ISSUE THREAD

**Issue by laurensmiers** [tass-belgium/picotcp#248]
When connecting a board running picoTCP to a C# app running on Windows, I noticed the following:
The app closes the connection and sends out a RST-ACK instead of the usual FIN handshake. picoTCP should close the socket when receiving the RST-ACK but does not. It is labeled an invalid flag and it keeps the socket open.

**Comment by maartenvds** [comment]
How to reproduce: sudo ./run.sh --test closebyreset-ackandreconnect testcases/hardware/tcp_close_bench_dut.txt

**Comment by laurensmiers** [comment]
Fix in commit 48bd994724373fecc11928e366a1dc2c0e800e72, waiting on confirmation of Quality

**Comment by S4mw1s3** [comment]
Hold on. Do we want to close the socket then? What in the case of sending out a SYN and receiving a RST,ACK and then later on on the same socket sending a SYN again and now receiving a SYN/ACK?

**Comment by laurensmiers** [comment]
The RFC states : RST: ... indicating that the receiver should delete the connection without further interaction. So I think we should close the connection.

**Comment by S4mw1s3** [comment]
Ok. Thanks for clarification :)
