### ISSUE TITLE
[PPP] Start/Stop character is sent in middle of lcp configuration reject message.

### ISSUE THREAD

**Issue by TassThomas** [tass-belgium/picotcp#282]
When trying to negotiate an LCP connection with PicoTCP, when Pico sends a LCP configuration reject message back, I see the STOP/START character (0x7e) in the middle of the packet being sent.

This character should be escaped, and should never appear in the middle of the message.

Reproduce by writing a unit-test for this.

**Comment by danielinux** [comment]
Unit test is in place. Please verify the fix.

**Comment by TassThomas** [comment]
Verified, it is working!
