### ISSUE TITLE
[PPP] IPCP reject messages not working properly

### ISSUE THREAD

**Issue by danielinux** [tass-belgium/picotcp#294]
If the DNS options are not supported by the peer, the remote IPCP continuously refuses the DNS options.

Fix by taking into account rejected options from the peer, and sending a new IPCP request without the rejected options.

@TassThomas -> please acknowledge the bug via RF tests if possible.

**Comment by TassThomas** [comment]
If wrote a quick RF test to check this behaviour, and indeed this is the case.
When pico sends an IPCP CONFIG-REQ to a peer, and the peer sends a CONFIG-REJ (indicating that a certain IPCP option is not supported) to pico, pico is still sending back the initial CONFIG-REQ back to the peer.. It does not adapt its CONFIG-REQ according to the CONFIG-REJ that it received..

In the PPPTest folder in the picotcp-rf repo, you can run the following:

./run.sh testcases/ipcp_test.txt
