### ISSUE TITLE
Slaacv4 does not pass bonjour conformance test (simultaneous probing)

### ISSUE THREAD

**Issue by cmahieu** [tass-belgium/picotcp#295]
When running the link-local test of the Bonjour conformance test suite v1.3.0 on pico it does not pass the simultaneous probing test.

A special picoTCP app (bonjour-conformance-test) is used which creates a tap0 device which is bridged to an iMac running the conformance test. After bridging, a slaacv4_claimip is done which results in the Bonjour test accepting the initial probe. The "probe denial" test also succeeds but the test stalls on the failing "simultaneous probes" test.

(The bonjour-conformance-test app has not yet been committed as this issue is mainly a reminder for Frederick Van Slycken. (at his own request))

**Comment by danielinux** [comment]
What are the plans for this? @frederikvs any follow-up actions needed? Is anyone assigned to this?

**Comment by frederikvs** [comment]
SLAACv4 passes the conformance test now, as of 60b226a7739b95875c06081d2a401e66961c7aa7. We still get warnings, but no errors. Closing.
