### ISSUE TITLE
dependencies between MCAST and IGMP?

### ISSUE THREAD

**Issue by frederikvs** [tass-belgium/picotcp#296]
Are PICO_SUPPORT_MCAST and PICO_SUPPORT_IGMP supposed to be dependent on each other or not?

Currently, a.o. in pico_ipv4.c we have places where an `#ifdef PICO_SUPPORT_MCAST ` surrounds igmp-related functionality (and calls to functions from pico_igmp.c). If MCAST is dependent on IGMP, then the makefile rules should enforce this. If MCAST was supposed to be independent, then the code should be modified so that it's actually independent. 
Or is there simply some confusion between when to use the ifdef for MCAST or for IGMP?

Also, pico_igmp.c is currently not protected by the `#ifdef PICO_SUPPORT_IGMP` I would have expected.

**Comment by danielinux** [comment]
What is the status on this? Anyone picking this up? Perhaps @roel0 has a better idea on how to organize the dependencies between IGMP/MLD/MCAST?
