### ISSUE TITLE
[PPP] When CHAP authentication fails, pico is trying to send PAP authentication message

### ISSUE THREAD

**Issue by TassThomas** [tass-belgium/picotcp#299]
When CHAP authentication was negotiated in LCP, and Pico is authentication itself and it receives an authentication-failure message followed by an LCP terminate request, Pico tries to authenticate itself with PAP authentication, instead of sending an LCP acknowledgement message.

The RFC says: If authentication fails, the authenticator SHOULD proceed instead to the Link Termination phase.

Reproduce:

./run.sh --test pppauthenticationfail testcases/

**Comment by danielinux** [comment]
Test should tolerate LCP_TERM_REQ as well...
