### ISSUE TITLE
pico_dns_sd_register_service fails with -1.

### ISSUE THREAD

**Issue by jonasvanpelt** [tass-belgium/picotcp#300]
pico_dns_sd_register_service fails with -1.

**Comment by phalox** [comment]
While trying to figure out what was going on, we noticed that the dns-sd autotest app doesn't run. Could this be checked so that we ensure the basic setup doesn't fail?

Do we also have a fully functional test ensuring that the operation is verified automatically?

**Comment by phalox** [comment]
Also, @jonasvanpelt just got ticket number 300!

**Comment by jelledevleeschouwer** [comment]
@jonasvanpelt congrats! :smile: Will check this tomorrow morning

**Comment by jonasvanpelt** [comment]
Thx!

2015-09-15 20:44 GMT+02:00 Jelle De Vleeschouwer <notifications@github.com>:
