### ISSUE TITLE
[DNS] When a CNAME response is found, the new request is incorrect.

### ISSUE THREAD

**Issue by danielinux** [tass-belgium/picotcp#305]
Example: try to resolve www.picotcp.com, get a CNAME response pointing to ext.squarespace.com. 

DNS module will try to resolve a new address ext.squarespace.\030\300 

DNS query fails.

**Comment by danielinux** [comment]
Apparently, IPv6 Only (related to AAAA records in CNAME)

**Comment by maximevince** [comment]
Closed in 05a12bf02126f5d304a34a83303e246f1f006c0a
