### ISSUE TITLE
TCP: Data acknowledged via FINACK at the end of the connection is ignored and retransmitted

### ISSUE THREAD

**Issue by danielinux** [tass-belgium/picotcp#310]
When in established state, a FINACK is received, FIN gets acknowledged, but the data acknowledged by the other endpoint is retransmitted.

One test showing this behavior.
To be verified...

**Comment by TassThomas** [comment]
reproduce this by performing the following:

./run.sh --test lastsegmenttobenchisackedinfinack

**Comment by maximevince** [comment]
Cannot reproduce with latest development...

**Comment by danielinux** [comment]
test has been rewritten, bug confirmed
