### ISSUE TITLE
[TAHI] Test v6LC.2.1.2: Resolution Wait Queue

### ISSUE THREAD

**Issue by pdvloed** [tass-belgium/picotcp#311]
Parts A and B failing (2:5 - 2:6)

**Comment by roel0** [comment]
Seems like a Tahi testing framework issue.

The testing node expects echo reply's after it has send its advertisement. And according to the capture file, this does happen.
[5_html_Link0.zip](https://github.com/tass-belgium/picotcp/files/550461/5_html_Link0.zip)

**Comment by phalox** [comment]
hi Roel, could you possible submit a bug report on the Tahi mailinglist (http://www.tahi.org/users/). Everyone would get better from this.

**Comment by roel0** [comment]
Done
