### ISSUE TITLE
dns pico_dns_rdata_cmp should compare bytewise

### ISSUE THREAD

**Issue by BrunoChevalier** [tass-belgium/picotcp#316]
For example:

compare 2 records' rdata containing:
record1: [0xC0 0xA8 0x01 0x5A]  (= 192.168.1.90)
record2: [0xC0 0xA8 0x01 0x7A]  (= 192.168.1.122)

Now when we execute pico_dns_record_cmp on these two records (assuming they both have the same name and type), we get a return value of 0, indicating they are equal, which they clearly are not.

The error is located in pico_dns_rdata_cmp. The function performs pico_tolower on each byte, which should not be done in the bytewise comparison.
The problem is that pico_dns_rdata_cmp is used in other methods too (pico_dns_record_cmp_name_type and pico_dns_question_cmp) and there the comparison should be done case-insensitive.

I suggest writing a different method to compare case-insensitive.
OR
Adjust the method to take a boolean indicating whether or not the comparison should execute the pico_tolower function. In this case the name of the function should probably be changed because the comparison is not really for rdata anymore, but for two general databuffers.

**Comment by danielinux** [comment]
If you are going to implement the second method, please use a int flag - not boolean.

**Comment by BrunoChevalier** [comment]
Should be fixed now
