### ISSUE TITLE
trailing white spaces in source code

### ISSUE THREAD

**Issue by mateuszviste** [tass-belgium/picotcp#324]
Hello, I noticed there are plenty of lines in picoTCP's source code that end up with white spaces. this is a little inconvenient, because my editor automatically trims such newlines (and this is a common configuration amongst developers), which leads to huge diffs each time I change anything in the code and click save.

It would be really nice if the picoTCP'd source code could be trimmed from such trailing white spaces in some automated way, before going to git.

**Comment by frederikvs** [comment]
I did a one-shot cleanup of this, but nothing automated yet.

For future reference, useful commands for trailing whitespace : 
checking if there is trailing whitespace (might be useful if we want to automate this test - return code tells us if there is trailing whitespace or not):
```
! find stack modules include -name "*.[ch]" | xargs grep "[[:space:]]$"
```
automatically deleting the trailing whitespace : 
```
find stack modules include -name "*.[ch]" | xargs sed -i ''  "s/[[:space:]]*$//"  
```

**Comment by fcapurso** [comment]
This is already done with uncrustify

**Comment by ISY-Thomas** [comment]
We have a static checks job in Jenkins, this job is checking all kinds of these things, so I have also just added this trailing whitespace check, for absolute certainty that we do not have these. 
If anything pops-up the job will fail, and let the culprit know!
