### ISSUE TITLE
DOS architecture support

### ISSUE THREAD

**Issue by mateuszviste** [tass-belgium/picotcp#327]
Here I provide my contribution - a patch that makes it possible to run picoTCP under 16 bit DOS. Tested successfully using the OpenWatcom compiler.

You are free to do whatever you wish with this.

[arch_dos.patch.txt](https://github.com/tass-belgium/picotcp/files/37817/arch_dos.patch.txt)

**Comment by danielinux** [comment]
please make a pull request ISO sending text patches.

**Comment by maximevince** [comment]
Fixed in f9ae356555d
