### ISSUE TITLE
disabling multicast leads to socket support failing

### ISSUE THREAD

**Issue by mateuszviste** [tass-belgium/picotcp#328]
I talked about this with Daniele Lacamera already, and I think he might have reported this (but I couldn't find any mention of that on this bug tracker, so here it is - just to be sure).

When I disabled multicast support, compilation of the socket unit failed. A bunch of ifdefs were missing. See the fix in attached patch.

[picotcp-no-mcast.patch.txt](https://github.com/tass-belgium/picotcp/files/37820/picotcp-no-mcast.patch.txt)

**Comment by danielinux** [comment]
please make a pull request ISO sending text patches.

**Comment by danielinux** [comment]
part of #323

**Comment by mateuszviste** [comment]
additional note: it is impossible to compile IPv6 support without including also IGMP and MLD.

**Comment by danielinux** [comment]
@roel0 can you have a look at this please?

**Comment by roel0** [comment]
Yes, I've planned this for this weekend

**Comment by danielinux** [comment]
wonderful :+1:

**Comment by roel0** [comment]
#323 is closed

**Comment by mateuszviste** [comment]
there still is something wrong in latest devel branch - the udp code tries to call pico_socket_mcast_filter(), even though I compiled it without multicast support. I wanted to compile a version with IPv6, but no multicast and no IGMP. see attached screenshot.

![mcast_filter_undefined_ref](https://cloud.githubusercontent.com/assets/9503501/11319790/a0211c7c-9083-11e5-8588-52639bde9885.png)

**Comment by mateuszviste** [comment]
and if I try to enable multicast (but not IGMP, nor MLD), I end up with this:

![igmp_mld_undefined_ref](https://cloud.githubusercontent.com/assets/9503501/11319816/4418c500-9084-11e5-8328-5736ba6f17d8.png)

**Comment by roel0** [comment]
I committed an additional fix to the development branch

**Comment by mateuszviste** [comment]
picoTCP with IPv6 but no IGMP nor multicast compiles and links fine now, thank you!
