### ISSUE TITLE
invalid assumption about int being 32 bits long

### ISSUE THREAD

**Issue by mateuszviste** [tass-belgium/picotcp#329]
in the `include/pico_constants.h` header, at line 34, I spotted this:
```c
#define PICO_IP4_BCAST (0xffffffffU)
```
I believe this is incorrect, because it assumes an unsigned integer will be able to hold such a big value, and that's untrue on many platforms.

It would be better to declare this as follows:
```c
#define PICO_IP4_BCAST (0xffffffffL)
```

**Comment by danielinux** [comment]
Why? it is  define, which will end up in a uint32_t...

**Comment by mateuszviste** [comment]
I'm not sure I understand your point.. the fact it is a ```#define``` doesn't automatically attribute a type - it's only a dumb string substitution performed by the pre-processor. The type indication is provided by the 'U' suffix, which means "unsigned integer", and those might be limited to 0xffff on some platforms.. have I missed something huge?

**Comment by danielinux** [comment]
I don't have a 16bit platform to test it on right now, but I am pretty sure it used to work on 8bit and 16bit. I am just assuming that the promotion takes place anyway because the suffix does not specify a size. Are you experiencing this kind of behavior with your compiler?

**Comment by mateuszviste** [comment]
I did some quick research in my copy of the bible, and I am pasting below the relevant fragment, that is 6.1.3.2 from ISO/IEC 9899:1990.

![9899-1990](https://cloud.githubusercontent.com/assets/9503501/11277000/bb4e90c4-8ee4-11e5-8bb2-c1fa98f67f9c.png)

The above proves you right - any constant suffixed with 'U' will get its type attributed to either an 'unsigned int' or 'unsigned long', whichever is big enough to hold the value. Hence I think you can safely disregard this thread, since indeed, 0xffffffffu is guaranteed by the standard to be stored in an 'unsigned long'. I'm sorry for having wasted your time.

PS. 0x00000000U, on the other hand (which appears in the same file), will therefore be assigned into an unsigned int, which might or might not lead to side-effects, depending in what kind of operations it will be involved.

**Comment by danielinux** [comment]
as long as the type cast is correct when the constant is used, this should not be a problem. Our QA is very strict about type conversions, so we can be quite sure this has no weird side effects.

As a side note: time spent looking at this issues is never wasted, so keep it flowing... ;)
