### ISSUE TITLE
pico_socket_connect() swaps the byte order of remote port number

### ISSUE THREAD

**Issue by mateuszviste** [tass-belgium/picotcp#330]
I am using the latest picoTCP version from the trunk on the svn repo. In my application, I call this:
```c
pico_socket_connect(sock, &srvaddr, 80)
```
and the result is... unexpected, to say the least :) see below:
```
# tcpdump -ni tapdosemu
15:51:11.224440 ARP, Request who-has 192.168.0.1 tell 192.168.0.22, length 28
15:51:11.224637 ARP, Reply 192.168.0.1 is-at 08:00:27:1c:0b:42, length 28
15:51:11.224947 IP 192.168.0.22.10370 > 185.86.53.5.20480: Flags [S], seq 826762308, win 6144, options [mss 1460,sackOK,wscale 0,TS val 54068025 ecr 0,nop,nop,nop,nop,eol], length 0
15:51:11.253029 IP 185.86.53.5.20480 > 192.168.0.22.10370: Flags [R.], seq 0, ack 826762309, win 0, length 0
```
Instead of using the remote port "80", picoTCP sets the dst port to 20480. Interestingly, 20480 is nothing else than (80 << 8). Out of curiosity, I tried this then:
```c
pico_socket_connect(sock, &srvaddr, 0x5000)
```
And then - miracle - the connection worked fine, using the correct port (ie. 80). Looks like some kind of endianess issue... As a workaround, I pass the port argument in network byte order, but I don't think this is what one is supposed to be doing. Maybe some htons() call is missing somewhere? I work on a little-endian platform (x86).

**Comment by danielinux** [comment]
Check the manual. The port argument needs to be in network byte order for all socket calls, as it happens in POSIX calls as well.

**Comment by danielinux** [comment]
ps: you can use short_be() which is equivalent to htons()

**Comment by mateuszviste** [comment]
I did read the manual :) http://docs.picotcp.com/user_doc.pdf (page 41, or 42 if looking at PDF paging)

The description of pico_socket_connect() doesn't say anything about passing the port in network byte order, it only say this:
> remote_port - Remote port number on which the socket will be connected to

I can understand of course it's not a bug then, if that's how it's supposed to be. I will know now, thank you for the clarification.

You are of course right about POSIX, as far as ```struct sockaddr_in``` is concerned. The usage difference is very subtle - personally, when I write something to a struct, I expect that I might have to use a specific format because structs tend to be bit-dumped as-is into files, streams, etc, but when passing a value to a function, I'd never think this value must be prepared in any specific way before hand. Well, anyway - that's just a matter of adding a short note to the manual I suppose, and then it will be perfectly clear for everyone. :)
