### ISSUE TITLE
"distributable" C headers generated at compile time?

### ISSUE THREAD

**Issue by mateuszviste** [tass-belgium/picotcp#331]
picoTCP comes with lots of *.h files which, obviously, are highly important. But I see a two-sides problem there.

1) The first problem I see here is that all these files contain much stuff that is irrelevant to the end-user of the library.
What I (as an end-user programmer) would expect, is to get some kind of headers that contain only the things I am supposed to be using through the documented picoTCP API.

2) Once I compiled "my" version of PicoTCP, I'd like to reuse it as a shared object in all my applications. But then, I must take care to compile every application with the exact same #define options that I used to compile PicoTCP initially, otherwise I won't get the correct headers.

It would be a real time saver if a distributable version of the headers were "compiled" at the same time than the picoTCP engine itself, so both headers and binary exactly match each other without the programmer having to remember the (long) list of definitions that needs to be declared for the headers to work correctly. This would solve the two problems (only API-related prototypes land inside the public headers + the headers contain exactly the same things as the binary library).

Even better - "all headers inside a single file" would be truly awesome. Why should the programmer worry about including all these files, when a single ```#include <picotcp.h>``` would be enough? Okay, I can understand this is too much to rant about :)

**Comment by danielinux** [comment]
1) The API exposed in the .h files come with different "depth" depending on how many of the internal functions will be used. For average use, the number of include files is pretty limited.
2) The best way to cope with this, is to integrate picoTCP by creating your set of defines. We normally do this by creating a pico_defines.h which already contains all the needed configuration. When distributing picotcp as a shared object, you should provide pico_defines.h as well in your include path. 

Of course, if this mechanism does not fit your needs, you could generate your custom headers, or even as a single "picotcp.h" file in a script that would fit the needs of your specific deploy.

As per the request, this is not going to happen in our official distribution as the format of the header files, the exposed API and the "normal" deploy mechanism cannot be altered or it would break compatibility for all our customers.   

Thanks for understanding...
