### ISSUE TITLE
IPv4 fragmented segments have different header ID's

### ISSUE THREAD

**Issue by maartenvds** [tass-belgium/picotcp#334]
When PicoTCP sends a packet that gets fragmented in 2 or more fragments, each fragment has a different IP header ID. This is not correct: all ID's of fragments that belong to one and the same packet should be equal.
This is an old bug but due to a bug in our test framework, it only was discovered recently.

Reference: RFC791 p27:
"For each datagram the buffer identifier is computed as the concatenation of the source, destination, protocol, and identification fields. If this is a whole datagram (that is both the fragment offset and the more fragments fields are zero), then any reassembly resources associated with this buffer identifier are released and the datagram is forwarded to the next step in datagram processing."

How to reproduce:
sudo ./run.sh --test icmpfragmentation testcases/hardware/icmp_bench_dut.txt

**Comment by laurensmiers** [comment]
I'm having trouble reproducing this issue. There is an IPv4 UDP fragmentation test in the autotest.sh file (https://github.com/tass-belgium/picotcp/blob/master/test/autotest.sh#L194) and when I execute this test, I see the correct behaviour as described in the RFC (all packets belonging to the fragmented packet have the same fragmentation ID).
Can you give some more information on the failing test? Thanks!

**Comment by ISY-Thomas** [comment]
Thanks for the investigation. Looking at the autotest.sh script output, it seems correct indeed.
Going to investigate what is happening, possible problem with the test framework.

**Comment by maartenvds** [comment]
This issue is reproduced by sending an ICMP ping packet with payload > 1500 bytes. The packet is therefor fragmented in 2 fragments. Pico needs to echo the packet with its full payload back (if fragmentation is enabled). This happens, but the id's are different.
For as far as I know, I double checked this in wireshark and its response was not correct. Maybe different config or scenario in the autotest.sh.

By the way, if fragmentation is disabled in this scenario, it should only send the first segment back and truncate the payload.

**Comment by ISY-Thomas** [comment]
Have been doing some testing and with the autotest executable I can reproduce the issue whilst performing an ICMP ping packet with payload > 1500.

I just launched a vde with the sock_start_user script:
 ./test/vde_sock_start_user.sh start

**next** launched: ./build/test/picoapp.elf --vde pic0:/tmp/pic0.ctl:10.50.0.8:255.255.0.0:::
**next** a ping to Picoapp: ping -I vde0 10.50.0.8 -s 1800 -i 2

And this is the tcpdump output:

09:01:44.612452 IP (tos 0x0, ttl 64, id 58777, offset 0, flags [+], proto ICMP (1), length 1500)
    10.50.0.1 > 10.50.0.8: ICMP echo request, id 1552, seq 1, length 1480
09:01:44.612482 IP (tos 0x0, ttl 64, id 58777, offset 1480, flags [none], proto ICMP (1), length 348)
    10.50.0.1 > 10.50.0.8: icmp
09:01:44.614574 IP (tos 0x0, ttl 64, id **37960**, offset 0, flags [+], proto ICMP (1), length 1500)
    10.50.0.8 > 10.50.0.1: ICMP echo reply, id 1552, seq 1, length 1480
09:01:44.614627 IP (tos 0x0, ttl 64, id **37961**, offset 1480, flags [none], proto ICMP (1), length 348)
    10.50.0.8 > 10.50.0.1: icmp

As you can see here the IP header IP is incremented with 1 for the fragmented parts of the echo reply..

**Comment by laurensmiers** [comment]
The problem seems fixed and autotest/unit tests run fine with me, can you guys verify?

**Comment by ISY-Thomas** [comment]
I have run the rf-tests with this fix, and the test (and wireshark, too) seem to agree that it is fixed! 
You did however merge this to master, so I will have a go with the development branch when it is merged back, before closing this issue.

Thanks, Laurens!!

**Comment by laurensmiers** [comment]
Ah damn.
Sorry for the boo-boo...

**Comment by ISY-Thomas** [comment]
And validated, thanks!
