### ISSUE TITLE
After 3 valid ARP replies from 3 different hosts, frames in the pending queue are accessed after being freed

### ISSUE THREAD

**Issue by danielinux** [tass-belgium/picotcp#340]
Reported by customer. Fixed in 86a5e6bbabee6370d1edb9647ea9bcde00480e32

**Comment by dekumans** [comment]
Added test 'arp reply multiple host' related to this bug in picotcp-rf-test. 
See https://github.com/tass-belgium/picotcp-rf-test/commit/282a973
Run for example with: sudo ./run.sh -t arpreplymultiplehost testcases/hardware/arp_bench_dut.txt
