### ISSUE TITLE
IGMP and MLD: code duplication

### ISSUE THREAD

**Issue by danielinux** [tass-belgium/picotcp#342]
see Tiobe TICS

**Comment by danielinux** [comment]
http://tics.picotcp.com:42506/tiobeweb/TICS/AnnotatedSource.html#metrics=Annotations%28DUPLICATEDCODE%29&path=HIE:PicoTCP_dev/master/modules/pico_mld.c

**Comment by roel0** [comment]
Fixed in cb61bed479d14f99e37ffe2cf335bba903d5b291
