### ISSUE TITLE
pico + http server lib loses memory in a wifi network with a lot of traffic

### ISSUE THREAD

**Issue by maximevince** [tass-belgium/picotcp#345]
On Jonas' ESP build, it seems picoTCP loses some memory about every 20 minutes.
It is connected on a WiFi network with a lot of traffic. 
Measurements take into account only PICO_ZALLOC and PICO_FREE calls (excluding the WiFi driver or any application). This mean only memory used by picoTCP itself or the HTTP server lib.

Next experiment is to run the example without HTTP server lib, to see if the leaks are coming from there.

![mem_table](https://cloud.githubusercontent.com/assets/3796135/11585631/be41dce8-9a6d-11e5-8780-ebc3512c6afa.png)

![plot](https://cloud.githubusercontent.com/assets/3796135/11585635/c1a2b8da-9a6d-11e5-8b72-e140365e8d1b.png)

**Comment by maximevince** [comment]
@jonasvanpelt

**Comment by danielinux** [comment]
How old is picoTCP on barlights? Can you reproduce the same on latest dev?

**Comment by jonasvanpelt** [comment]
@danielinux I ran the test this night with the latest pico dev version. This weekend I'm gonna do the test without the HTTP lib.

**Comment by danielinux** [comment]
@jonasvanpelt  thanks. So depending on your tests, either we confirm this bug here or we open one against libhttp.

**Comment by maximevince** [comment]
There was an issue with the measurements this night. Closing issue until further details are available.
