### ISSUE TITLE
pico_tap_create increases mac[5] with 1.

### ISSUE THREAD

**Issue by StefanKoppier** [tass-belgium/picotcp#347]
Is the `mac[5]++` at https://github.com/tass-belgium/picotcp/blob/master/modules/pico_dev_tap.c#L206 intended behavior?

**Comment by danielinux** [comment]
Yes. When the TAP device is created, its mac address generated by the host on its endpoint is retrieved via `tap_get_mac()`. To act as a second endpoint in the same subnet, the picoTCP app using the tap device must have a different mac address. For simplicity, we just add 1 to the last byte of the linux endpoint so the two addresses are consecutive.

**Comment by phalox** [comment]
Maybe a comment in the code coule be useful?
