### ISSUE TITLE
[6LoWPAN] mesh ping mechanism is not robust towards packet loss

### ISSUE THREAD

**Issue by danielinux** [tass-belgium/picotcp#348]
Also, we suspect that the `sixlowpan_ping_check()` timer is never retriggered, so if a ping gets lost, there is no way to recover the via to the neighbor.

**Comment by jelledevleeschouwer** [comment]
@danielinux is it okay that I will look into to it after my exams? I don't really have time for it at the moment. About that sixlowpan_ping_check, it is indeed not retriggered but I already mentioned this in f2b04b2f025d5838a00fe03651d7eb68f5aaced7. But I'd like to refactor the routing-table maintenance anyway as described in #217.

**Comment by jelledevleeschouwer** [comment]
And I thought it over recently, but I think the routing-table maintenance doesn't even need timers anyway. Unless for a timeout.

**Comment by danielinux** [comment]
No pressure intended, :) Opened the issue only to keep track of this.

We need to be sure we can test multi-hop routing (mesh composition) with high packet loss (5~10%). In that case, it seems that ping retries need to be implemented anyway.

If we try and retrigger the `sixlowpan_ping_check` manually, it seems that there's a loop of (undetected) duplicates going on.

We'll investigate furter.
Thanks

**Comment by phalox** [comment]
@jelledevleeschouwer @S4mw1s3 What with this issue?

**Comment by jelledevleeschouwer** [comment]
@S4mw1s3, did you still encounter a lot of packet loss with the demo?

Routes are now reconfirmed multiple times before the TTL expires, I don't really think there's more that we can do. If there's no reach, there's no reach. As far as I'm concerned this issue can be closed.
