### ISSUE TITLE
fragments cyclomatic complexity

### ISSUE THREAD

**Issue by frederikvs** [tass-belgium/picotcp#366]
TICS reports cyclomatic complexity for pico_fragments.c is too high.
Find a way to decrease it, while increasing code quality.

Small note : cyclomatic complexity isn't a target in and of itself. If you find that you're making changes, thinking "this is crap, but it'll get the complexity down", please stop and let us know...

**Comment by jelledevleeschouwer** [comment]
:+1: for the note :-)

**Comment by laurensmiers** [comment]
Will have a look at this if that's OK with you guys?

**Comment by BrunoChevalier** [comment]
Sure, that's OK.
I pushed some changes to the mdns_wip branch on Friday, just so you know.

**Comment by swendrickx** [comment]
I was taking a look at that as well but since you already worked on it. It
might be best if you do it.
Op 21-feb.-2016 12:10 schreef "Laurens Miers" <notifications@github.com>:

**Comment by BrunoChevalier** [comment]
Woops, I just noticed that this is about pico_fragments and I was talking about mdns.
Anyway, its cyclometric compexity is also too high, but that should be discussed in a different issue.

**Comment by frederikvs** [comment]
@swendrickx : always self-assign an issue before getting to work. But don't worry, there's plenty of cyclomatic complexity to go around. I've added issues for the next worst files in line, #368, #369. Feel free to pick up any one of those :-)

BTW, @laurensmiers don't forget to add unit tests if/where necessary.

**Comment by frederikvs** [comment]
@laurensmiers  how's this coming along?
If you've made some progress, and would like to get it into the dev branch, be sure to make a pull request.

If you're still working on it, and it's not ready yet, no problem. I just want to avoid the situation where you think it's done, and I'm waiting for the pull request :-)

**Comment by frederikvs** [comment]
PR #374 improved this quite nicely.
TICS cyclomatic complexity score is better, but still isn't great. Looking at the code however, it isn't all that complex, so this looks like another confirmation that that mccabe's metric might not be the best tool to use.

Closing, nice work :-)
