### ISSUE TITLE
libpcap driver integration problem help

### ISSUE THREAD

**Issue by jack2007** [tass-belgium/picotcp#372]
Hello,

I'm integrating picotcp with libpcap driver on Ubuntu 14.04 Linux, I have make it running successfully with the built-in libpcap driver code. It's in modules/pico_dev_pcap.c.

Because I only want to use the TCP function for web server, I add  pcap filter into pico_dev_pcap.c->pico_pcap_create, like below
```
pcap_compile(pcap->conn, &fp, "tcp dst port 80", 1, 0);
pcap_setfilter(pcap->conn, &fp);
```
With this pcap filter, pico_stack_recv only receives TCP packets, and then picotcp can't establish incoming connection request. When I remove this filter code, everything works fine.

It looks like picotcp needs some packetsother than pure TCP packets to serve TCP connection. (just my guess)

My question is If I only need TCP function for web, should I capture all  the packets on the eth card or I can filter some unrelated packets?

Thanks

**Comment by danielinux** [comment]
Perhaps you also need to add ARP or ICMP6 to your filters too, depending whether you are using IPv4 or IPv6.

**Comment by jack2007** [comment]
I'm using IPv4. I'll try your suggestion.
Thanks.

**Comment by jack2007** [comment]
@danielinux   I added arp into my filter. 
It works, thanks very much.
