### ISSUE TITLE
TCP connection mss negotiation failed

### ISSUE THREAD

**Issue by jack2007** [tass-belgium/picotcp#373]
Hi, 
I think I find a bug that picotcp negotiates mss with peer not correctly.

Below is the current code in pico_tcp.c:tcp_syn()
```
    f->sock = &new->sock;
    tcp_parse_options(f);
    mtu = (uint16_t)pico_socket_get_mss(&new->sock);
    new->mss = (uint16_t)(mtu - PICO_SIZE_TCPHDR);
```
When picotcp acts as a tcp server and receives a syn, if peer's mss is less than picotcp, picotcp assigns peer's mss to t->mss in tcp_parse_options(f), and the next 2 lines of code overwrite it to picotcp's local mss again. This bug cause picotcp cannot talk to peer.
After I change the code to the below, it works fine.
```
    f->sock = &new->sock;
    mtu = (uint16_t)pico_socket_get_mss(&new->sock);
    new->mss = (uint16_t)(mtu - PICO_SIZE_TCPHDR);
    tcp_parse_options(f);
```

**Comment by maartenvds** [comment]
Thanks for spotting!
@tass-belgium/qa-team This is also an RFC violation. We also need to add a compliance test case for this

**Comment by frederikvs** [comment]
Thanks for noticing! Bug is fixed in development branch.
