### ISSUE TITLE
[pico_device] - overhead-member implemented?

### ISSUE THREAD

**Issue by jelledevleeschouwer** [tass-belgium/picotcp#376]
Is the purpose of the overhead-member in the pico_device-structure actually implemented? Since I can't find an occurance anywhere of an allocation of a frame (or buffer) where the overhead-member is taken into account. The wiki states that this is done in the network-layer but I can only find an allocation that takes the Ethernet header-size into account ([IPv6 for example](https://github.com/tass-belgium/picotcp/blob/master/modules/pico_ipv6.c#L873)), which is sufficient for my usecase, but maybe it should be either implemented or removed :)

Best regards,
Jelle

**Comment by frederikvs** [comment]
was closed by #406
