### ISSUE TITLE
return value of pico_tree_insert

### ISSUE THREAD

**Issue by frederikvs** [tass-belgium/picotcp#380]
There are many locations in the stack where we use `pico_tree_insert`, without checking its return value. This is wrong. `pico_tree_insert` can fail if we're out of memory, or if the key is already in the tree. 

In both cases, generally, you need to free the memory you were trying to insert, and probably signal an error upwards. 

Use e.g. `ag pico_tree_insert include stack modules` to find all occurrences of `pico_tree_insert`, see about fixing them...

**Comment by frederikvs** [comment]
@VincentDeHaen what progress have you made with this issue?

**Comment by VincentDeHaen** [comment]
I had the time to finish it today and send a pull request. Hope it's worth something ;)

**Comment by frederikvs** [comment]
was fixed by #386
