### ISSUE TITLE
coverity scan issues

### ISSUE THREAD

**Issue by frederikvs** [tass-belgium/picotcp#381]
We have access to coverity scan, a static analysis tool that gives quite extensive feedback.

Currently it's reporting about 30 issues. We should take a look, see which problems are easy to fix (and fix them), and which require more work (and open a new issue here on github).

Note that this tool may (or may not) give false positives. Again, don't make changes just to please the tool, but use the tool to improve the code!

If you feel like taking this up, contact me for access.

**Comment by frederikvs** [comment]
note that there may be some overlap between #380 and this one.

**Comment by matthiasvp** [comment]
I analyzed the open issues, there were quite a few false positives, and fixed the actual bugs.
@ISY-Thomas also set up Jenkins to run Coverity every night.
