### ISSUE TITLE
Constant retransmission of the same TCP frame

### ISSUE THREAD

**Issue by fjullien** [tass-belgium/picotcp#393]
Hi,

I'm porting a firmware from LwIP to picoTCP. I'm working on a STM32F4.
I got the stack partially working. Until now, ping works.

You'll find a Wrireshark capture of the problem here: [http://picpaste.com/pics/pb-7TX4D1sa.1469451465.png
](url)

My problem is with TCP. My application is an HTTP server (192.168.1.82 in the capture). When the client ask for a file, the server sends it using a socket. Then pico_tcp_process_out --->pico_network_send is called one time only. However, the frame gets sent (my ethernet hardware send function being called) continuously.

I'm currently working on this problem. However, if you got any insight that could be helpful.

Thanks in advance.

Franck.

**Comment by fjullien** [comment]
It might be because the stack doesn't get or discard ACK frames.

**Comment by maximevince** [comment]
Hey Julien,

You ethernet_send function needs to return the amount of bytes that were actually transmitted,
such that picoTCP knows those bytes were actually sent.

You can return 0 when the ethernet hardware was unable to send the bytes at that time;
This will make picoTCP retry in the next tick. 
This sounds like the problem you are describing: continuously calling your ethernet_send function.

**Comment by S4mw1s3** [comment]
For more information about picotcp device drivers you can take a look at this wiki page: https://github.com/tass-belgium/picotcp/wiki/device-drivers#send-function

**Comment by fjullien** [comment]
@maximevince, you found my problem. While porting the code I just did retval = len at the end of my send function. Unfortunatly, retval was a signed char...

Thanks for saving me some time.

Franck.

**Comment by frederikvs** [comment]
@maximevince thanks for the quick reply!

@fjullien I think this means I can close this issue? 
If something still doesn't work, feel free to open another issue (or reopen this one, if it turns out it still isn't fixed) :-)

**Comment by phalox** [comment]
@fjullien Keep us posted on your work! We're always curious to see what people do with the stack.
