### ISSUE TITLE
libsubunit needed

### ISSUE THREAD

**Issue by frederikvs** [tass-belgium/picotcp#421]
When compiling the unit tests under ubuntu 16.04, we need to add a flag `-lsubunit` to our linker. This was done by @BrechtDeVlieger in PR #418 .
However, turns out that on other systems (including ubuntu 14.04), adding this flag causes linker errors, because it cannot find -lsubunit...

So yeah, guess we will need to figure out a way of deciding whether or not -lsubunit is necessary or not.

**Comment by phalox** [comment]
@BrechtDeVlieger I'm running ubuntu 14.4 which failed before. If I install 

sudo apt-get install libsubunit-dev 

The code works. This means that the pre-requisites should be updated everywhere. Please do so in getting started guides, README.md and wiki files

**Comment by frederikvs** [comment]
Looking at it a bit more in depth, I'm guessing that libcheck silently added a dependency to libsubunit somewhere between version 0.9.10 (on my ubuntu 14.04), and 0.10.0 (as seen in their documentation [0] ).

On ubuntu 14.04 this dependency wasn't there yet, so everything worked. On ubuntu 16.04, with a more recent version of check, the dependency is there, so we need to add the linker flag. Back to ubuntu 14.04 with this linker flag, if the linker can't find the lib, it'll give an error.
So yeah, just installing `libsubunit-dev` on 14.04, as @phalox suggested, is a workaround. Stupid really, because on 14.04 we don't really need that package, but every other workaround I can think of is far more ugly.


[0] https://libcheck.github.io/check/doc/check_html/check_4.html#Advanced-Features

**Comment by frederikvs** [comment]
also, @ISY-Thomas , could you just `apt-get install libsubunit-dev` on the jenkins machines? So that the tests pass again?

**Comment by laurensmiers** [comment]
Just adding this for completion:
I'm using Manjaro (Arch Linux derivative). There was no subunit in pacman/yaourt (only the python implementation) so I had to make and install the library manually ([subunit](https://launchpad.net/subunit)).

**Comment by ISY-Thomas** [comment]
@frederikvs Done! Unit tests all passing again!

@laurensmiers Thanks for letting us know this, very helpful info!

**Comment by maximevince** [comment]
At some point you might consider adding the dependencies to your build system, and linking them in statically.
Just add the check + subunit repo's as git submodule, build them (once), then statically link with the version you just built. No rpm/apt/pacman/yum/... distro-hell.

**Comment by laurensmiers** [comment]
It seems that libsubunit is not required on Manjaro (Arch Linux). As far as I know, subunit is only required on Ubuntu derivatives. We should be able to detect this and include the subunit if needed. Or use maximevince solution (but sounds like more work :))

**Comment by roel0** [comment]
Should be fixed in  84c2da5
