### ISSUE TITLE
Unnecesary malloc

### ISSUE THREAD

**Issue by phalox** [tass-belgium/picotcp#438]
https://github.com/tass-belgium/picotcp/blob/6LoWPAN_dev/stack/pico_frame.c#L75

How often do we execute this function? I believe we can just put the malloc in the else case, right?

**Comment by BrunoChevalier** [comment]
I think this fixes what you meant: https://github.com/tass-belgium/picotcp/commit/afc87750121590165b205d5d46100aa318a98226

**Comment by phalox** [comment]
Indeed!
Would be nice to have tools that could tell us how frequently this line is touched, and see how performance changes by this change :-) (something for the future maybe?)

**Comment by BrunoChevalier** [comment]
We can always do some measurements with gprof, callgrind and Massif to see the impact on memory and cpu usage. All calls that have ext_buffer defined, without specifying zero_copy will benefit from this change. But as you say, I don't know how much that scenario occurs.
I'm going to close this for now and I'll see if I can setup some more measurement infrastructure.

For example busybox keeps track of the size impact of all changes and takes this into account when evaluating new changesets. Maybe we can add this for picotcp too?
