### ISSUE TITLE
Thread-safety

### ISSUE THREAD

**Issue by ProgVal** [tass-belgium/picotcp#452]
Hi,

What are the limitations to using picotcp with multiple threads?

In particular, is there a way can I use `pico_err` after a pico function returns `-1`, if `pico_err`  may have been set by an other thread at the same time?

(Sorry if this is already documented somewhere, but I could not find anything related to threads in picotcp other than [in the porting guide](https://github.com/tass-belgium/picotcp/wiki/Porting-picoTCP-OS#mutexes).)

Thanks!

**Comment by danielinux** [comment]
Hi there! This is a very interesting question, and it'd be nice to hear some official guidelines in this regard.

The following comes from my personal experience integrating picoTCP with RTOS:
PicoTCP has support for RTOS mutexes that can be implemented by defining `pico_mutex_init` , `pico_mutex_lock` and `pico_mutex_unlock` functions, which will be used by the stack automatically to protect queues when `PICO_SUPPORT_MUTEX` is defined. Those mutexes protect internal queues from multi-threaded access, but are not sufficient to prevent other critical situations (e.g. socket create/destroy, pico_err override, etc.).

My approach when implementing this in frosted OS is the following:
- Run pico_stack_tick from within a kernel thread
- Wrap native calls into system calls (which are run in the syscall context of the calling thread)

This is relatively easy to implement, but it requires locking on a global mutex to ensure that the shared structures are not corrupted. The validity of pico_err can also be limited within the call context, i.e. in critical sections. The hardest part is finding the right way to implement blocking calls, as the mechanism may vary depending on the OS architecture.

In pseudo-code, my usual approach boils down to:

**Main TCP/IP thread**
```
while(1) {
    acquire_global_lock();
    pico_stack_tick();
    release_global_lock();
}
```

**Socket thread/call wrapper**
```
int accept(int fd, struct sockaddr *addr, socklen_t *alen) {
    /* ... */
    acquire_global_lock();
    newsock = pico_socket_accept(/* ... */);
    if (!newsock)
        errno = pico_err;
    release_global_lock();
    /* ... */
}
```

Some examples can be found at:
- [picoTCP-bsd: official OSAL repository](https://github.com/tass-belgium/picotcp-bsd)

- [frosted INET socket implementation](https://github.com/insane-adding-machines/frosted/blob/master/kernel/drivers/socket_in.c)

- [frosted custom pico_port.h](https://github.com/insane-adding-machines/frosted/blob/master/kernel/pico_port.h)

**Comment by frederikvs** [comment]
Hi, I apologise for the delay in getting back to you. Earliest Deadline First scheduling is not kind to tasks without a strict deadline...

I'm afraid that at this moment, there are no real safeties on threading and pico_err. When a picoTCP function encounters a problem, it sets pico_err, and returns. If another thread runs another picoTCP function and also encounters a problem, it will override that.
Maybe it would be an option to consider using Thread Local Storage (standardised in C11)?

Internally, when we work with threads, it's most often just one picoTCP thread (running stack_ticks all the time), and one main-thread doing socket calls, much as @danielinux described. Theoretically it should be possible to do much more with threads (e.g. run each protocol layer in its own thread, separated by the queues, protected by the mutexes), but we don't use this internally, so there might be some skeletons in the cupboard there.
