### ISSUE TITLE
`pico_string_to_ipv4` accepts bytes greater than 255

### ISSUE THREAD

**Issue by ProgVal** [tass-belgium/picotcp#453]
When calling `pico_string_to_ipv4` with a string like `"10.10.10.258"`, it does not error.

The following code:

```c
#include <stdio.h>
#include <stdint.h>
#include "pico_ipv4.h"

void main() {
    uint32_t ip4;
    char buf[17];
    pico_string_to_ipv4("10.10.10.259", &ip4);
    printf("%x\n", ip4);
    pico_ipv4_to_string(buf, ip4);
    printf("%s\n", buf);
}
```

prints:

```
30a0a0a
10.10.10.3
```

(the 3 is 259 modulo 256)

I am not sure if this is a bug or a feature, but I could not find a reference to this behavior in the documentation.

**Comment by roel0** [comment]
Well in POSIX, inet_addr() returns -1 on invalid address, so you have a valid point!
Thanks for reporting, fixed
