### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by ifelsedeveloper** [tass-belgium/picotcp#471]
Hello,
I am trying to connect to TCP server with the help of picotcp. I get error "No route to host".
Is this an error or I missed something?

`

    pico_stack_init();
    uint8_t ttl = 20;
    int i = 0, ret = 0, yes = 1;
    uint16_t send_port = short_be(port);
    struct pico_ip4 dest = {
        0
    };
    pico_string_to_ipv4(hostName.toStdString().c_str(), &dest.addr);

    buffer0 = malloc(TCPSIZ);
    buffer1 = malloc(TCPSIZ);

    m_socketError = QAbstractSocket::SocketError::UnknownSocketError;
    LOG(INFO) << "PICO: Connecting to host = " << hostName.toStdString().c_str() << " port =" << port;
    //intialize socket
    m_socket = pico_socket_open(PICO_PROTO_IPV4, PICO_PROTO_TCP, NULL /*&cb_tcpclient*/);
    if (!m_socket) {
            LOG(INFO) << "connectToHost error opening socket: " << strerror(pico_err);
            m_socketState = QAbstractSocket::SocketState::UnconnectedState;
            m_socketError = QAbstractSocket::SocketError::NetworkError;
            emit error(m_socketError);
            return 1;
    }

    //pico_socket_setoption(m_socket, PICO_TCP_NODELAY, &yes);

    //set socket options
    //LOG(INFO) << "PICO: set socket options ttl = " << ttl;
    //ret = pico_socket_setoption(m_socket, PICO_IP_MULTICAST_TTL, &ttl);

    //connect to ip and port
    LOG(INFO) << "PICO: pico_socket_connect ";
    ret = pico_socket_connect(m_socket, &dest, send_port);
    if (ret < 0) {
       LOG(INFO) << "PICO: pico_socket_connect error " << strerror(pico_err);
       m_socketError = QAbstractSocket::SocketError::NetworkError;
       emit error(m_socketError);
       return 1;
    }
    LOG(INFO) << "PICO: Connected successfully to host = " << hostName.toStdString().c_str() << " port =" << port;
    return 0;`

**Comment by danielinux** [comment]
Are you adding a network interface? Are you configuring your interface via pico_ipv4_link_add() ?

**Comment by ifelsedeveloper** [comment]
I was trying to use pico_ipv4_link_add but unfortunately I can't get device for real network interface.
How can I do this?

**Comment by danielinux** [comment]
You need a device driver for your network device.

**Comment by ifelsedeveloper** [comment]
I have virtual box and my virtual machine(Virtual Box) has it's own network driver(Ubunutu 16.04). I can use it to connect to internet. 
Do you mean that we need to use the another socket implementation? Or we need to put device info into structure? Could you please clarify?

**Comment by roel0** [comment]
You can find [an example ](https://github.com/tass-belgium/picotcp/wiki/Examples)on our wikipage on how to get started on Linux
