### ISSUE TITLE
Pico TCP http application

### ISSUE THREAD

**Issue by IfrahIdrees** [tass-belgium/picotcp#476]
Is there any application that uses picoTCP stack and gets a html page and displays it. Like a simple client and server and has such an application been tested before?

If not can somebody guide me as to how to build such a client server. I am new to picoTCP and want to explore it therefore any help will be highly appreciated.

**Comment by maximevince** [comment]
A good starting point is probably https://github.com/tass-belgium/picotcp-modules/tree/master/libhttp
This is not a complete demo application, however. But it should get you going.

**Comment by IfrahIdrees** [comment]
Thank you so much for the library. I have trying to work around this library and tcp client example.
