### ISSUE TITLE
TCP Client example

### ISSUE THREAD

**Issue by IfrahIdrees** [tass-belgium/picotcp#477]
For a week or so I have been trying to work with http library of picoTCP. Moreover, I have been trying to make tcp client example work, however in my case the client does not connect to any private or public ip address. It gives a connection timeout address. Any heads up in this regard. Your help will be highly appreciated.

**Comment by roel0** [comment]
#476 duplicate

**Comment by phalox** [comment]
You might have closed one too fast :-) @IfrahIdrees can you give us more information. What are you trying to run the demo on? Can you describe your steps taken?

**Comment by IfrahIdrees** [comment]
I have a x86-64 linux machine. I have been able to compile and run the ping and tcp echo examples so far. My final goal is to measure performance of http applications that use pico TCP stack so as a first try I tried to run the tcp client example but wasn't successful in running it.
With regards to run this specific example, the steps that I took are as follows:
I created a persistent tap on a private ip address say 192.168.13.37 and started a netcat server  it using the following command:
nc -l -p 80
On another terminal I ran the tcp client using the following command:
sudo ./build/test/picoapp.elf --tun myTun:192.168.13.38:255.255.255.0 --app tcpclient:192.168.13.37:80.
However, the client does not get connect to the netcat server. I even tried  connecting it to the tcpecho server but it always gives the following error: 
"TCP> Connection timeout. 
Socket error received: Connection refused. Bailing out."
@phalox  I have even tried increasing the pico_timer but nothing worked. By default it was 2000. Can you tell me what am I missing.

**Comment by phalox** [comment]
Bit of extra information from @IfrahIdrees :

I tested running this example using both tap and tun adapters while using a tap device for the server. But none of the adapters work.

I have previously ran both the ping and tcp echo example (https://github.com/tass-belgium/picotcp/wiki/Examples (picoapp.elf section)), they both work for me but not the tcp client example.

Really looking forward to getting a positive response well in time that will help me move forward in my project.

**Comment by roel0** [comment]
Seems to be an issue. At first sight the send port is never inserted inside the TCP table, will investigate it further in the comming days..

**Comment by phalox** [comment]
@IfrahIdrees ping!

**Comment by IfrahIdrees** [comment]
Hey thank you so muchh. Means a lot.

Yes I was doing pretty much the same thing. The only thing that was different was that I was making a presistent tap device without giving it the switch -t and the name for the device and further was listening at port 80. Does the switch -t or port make any difference?
 
The commands that I used were:

`$term1 sudo tunctl -u $USER`
`$term1 sudo ifconfig tap0 192.168.13.38`
`sudo nc -l -p 80`
`sudo ./build/test/picoapp.elf --tap myTap:192.168.13.37:255.255.255.0 --app tcpclient:192.168.13.38:80`

Can you explain why do my commands not work and yours do?

P.S Your command seem to work on my laptop aswell. Is the tcp client expected to shut down unexpectedly by itself?

**Comment by roel0** [comment]
Because your starting the tcpclient attached to a new tap device **myTap** instead of the **tap0** device created wit tunctl :)
Yes thats normal, you can compile with INFINITE_TCPTEST to override that behaviour.
