### ISSUE TITLE
[UDP] broadcast traffic cannot be received if MCAST support is off

### ISSUE THREAD

**Issue by danielinux** [tass-belgium/picotcp#479]
There is a regression in udp (unicast) sockets. Broadcast traffic cannot be received if `PICO_SUPPORT_MCAST` is disabled, and the socket is bound locally (works OK if the socket is bound to INADDR_ANY).

Removing the `#ifdef PICO_SUPPORT_MCAST` statements from pico_socket_udp.c fixes the problem. I guess that commit 146a39f8755b18bc1f494a38956db1660864a844 introduced the problem.

Please allow broadcast traffic on UDP sockets even when multicast support is not compiled in.

cc: @roel0

**Comment by roel0** [comment]
I was indeed a bit strict, should be resolved now!
