### ISSUE TITLE
Memory Usage increase after ever disconnect and reconnect

### ISSUE THREAD

**Issue by FaMo4059** [tass-belgium/picotcp#483]
Hi, 

I am currently trying picoTCP with PPP connection on a cortex M4 device with ublox modem and freeRTOS , It works pretty flawless but I have noticed that after every disconnection and new connection establishment a little more heap is used. I have tried both, deleting the socket and destroying pico device after disconnect and create new device and socket to reconnect; and to only disconnect the device and reconnect with the same picoDevice but I ran into the same problem. any Ideas or if I am implementing it wrong?
Another question do you plan to support static memory allocation soon I have tried to use the provided  Memory manager but it used a lot more memory.

Thanks

**Comment by jelledevleeschouwer** [comment]
Hi @FaMo4059,

- Could you please provide us with some more details about your issue so we can reproduce the observed behaviour? How exactly do you close and reopen the socket, and how exactly do you destroy and recreate a new pico_device?
- The memory manager indeed allows you to restrict the amount of memory in use by the stack. The stack itself will internally always use dynamic memory allocation, though when the memory manager is enabled, use pages allocated by the memory manager instead. The memory manager itself still depends on a **malloc**/**free**-interface but making the implementation a lot easier by only allocating fixed size elements. For more details on how to use this interface together wit h a static buffer, check [this thread](https://github.com/tass-belgium/picotcp/issues/371#issuecomment-248078895). We still have an open [issue](https://github.com/tass-belgium/picotcp/issues/416) to make static memory allocation standalone, thus with depending on malloc/free.

**Comment by ThomasNauwelaerts** [comment]
@jelledevleeschouwer 
When closing the socket, no memory is freed. Is that normal?

**Comment by jelledevleeschouwer** [comment]
@ThomasNauwelaerts 
That does indeed not appear to be normal. I'll continue our conversation over mail as that maybe speeds up the debugging process.

**Comment by ThomasNauwelaerts** [comment]
My problem is solved with the commit of Jelle.
