### ISSUE TITLE
Memory leak not merged

### ISSUE THREAD

**Issue by ThomasNauwelaerts** [tass-belgium/picotcp#487]
Memory leak of https://github.com/tass-belgium/picotcp/commit/81cde92b3c12cc4f753dc8fefd4801e1abaa2e7c has not been merged to master.

**Comment by jelledevleeschouwer** [comment]
Cherry-picked in [46120abecc9fb79f7dfb2cc8192341a42e40fc8b](https://github.com/tass-belgium/picotcp/commit/46120abecc9fb79f7dfb2cc8192341a42e40fc8b). Closing this bug.
