### ISSUE TITLE
pico ipv4 link find() does not find tap0 on linux machine

### ISSUE THREAD

**Issue by yogk** [tass-belgium/picotcp#492]
Hi,
We are experimenting 2 requirements with picoTCP. Not sure if this is a problem of PicoTCP or not. But I hope to get some info.
1.) PicoTCP must be able to read/write the data to/from tap0 interface created on a linux machine.
2.) PicoTCP must be able to read/write the data to/from tap0 interface bridged with eth0. As tap0 here is bridged with the NIC eth0, we expect to talk to all the other devices on the same LAN. i.e able to exchange data with other devices on the same network. 

If 1.) works then hopefully even 2.) works.
For testing 1.), I created a tap0 interface on Linux machine and assigned it with some IP. Modified the simple ping example to read the tap0 of linux machine. However when I call
` dev = pico_ipv4_link_find(&linux_tap_ipaddr); 
`
it always results in printf("FAIL to find tap dev of linux!!!\n");

Here is the full code for reference.

``
int main(void){
    int id;
    struct pico_ip4  netmask, linux_tap_ipaddr;
    struct pico_device* dev;

    /* initialise the stack. Super important if you don't want ugly stuff like
     * segfaults and such! */
    pico_stack_init();

    /* Find the linux tap address. Assigned 192.168.82.101 for tap0 on linux */
    pico_string_to_ipv4("192.168.82.101", &linux_tap_ipaddr.addr);
    dev = pico_ipv4_link_find(&linux_tap_ipaddr);

    if(!dev)
    {
         printf("FAIL to find tap dev of linux!!!\n");
         return -1;
    }
   
    pico_string_to_ipv4("255.255.255.0", &netmask.addr);
    pico_ipv4_link_add(dev, linux_tap_ipaddr, netmask);

    printf("starting ping of eth0 interface on same machine\n");
    id = pico_icmp4_ping("192.168.82.100", NUM_PING, 1000, 10000, 64, cb_ping);

    if (id == -1)
        return -1;

    /* keep running stack ticks to have picoTCP do its network magic. Note that
     * you can do other stuff here as well, or sleep a little. This will impact
     * your network performance, but everything should keep working (provided
     * you don't go overboard with the delays). */
    while (finished != 1)
    {
        usleep(1000);
        pico_stack_tick();
    }

    printf("finished !\n");
    return 0;
}
``

Please let me know if pico ipv4 link find() is the right way of using picoTCP API to find an IP addr on Linux machine.
As I want picoTCP running on linux to communicate with other machines on the same network when we implement our requirement 2.) do i need to make other changes in picoTCP to get it working ?

Regards
YK

**Comment by frederikvs** [comment]
You should be using the function `pico_tap_create` to get the device.
For a complete example of how to use tap devices, please see https://github.com/tass-belgium/picotcp/wiki/Examples

**Comment by yogk** [comment]
Hi frederikvs,
thanks for reply.
hey I have seen this example and that is ok (it works for me too) . I do not want to create a tap device inside picoTCP as shown in the example. If you read my question, I want to use the tap0 device of my linux machine and not pico_tap_create() to create a tap0 device in picoTCP.

Hope my question is clear ?

I basically want picoTCP to interact with packets received/transmit from tap0 of my linux machine to the external world i.e. other machines on the same network.

A picture would give a better idea

![img_20190123_195928](https://user-images.githubusercontent.com/6000402/51630244-f7160580-1f49-11e9-96f0-d4eb4946937f.jpg)

Sorry the picture has the shadow of my mobile :)

Is this scenario possible to read/ write traffic from local LAN. I feel I need to use bridge between eth0 and tap0 to TX and RX LAN traffic . As seen from the picture PicoTCP will read /write the frames from/to  tap0 interface 

Regards
YK

**Comment by frederikvs** [comment]
@yogk I think you'll have to use `pico_tap_create`. However, it should be possible to take the tap device created by picoTCP, and add that to a bridge.

Or create a persistent tap device
```
sudo tunctl -u <username>
sudo ifconfig tap0 192.168.5.5
```
add that to the bridge, and then use `pico_tap_create` to open that tap device.

Any particular reason why you're trying to avoid `pico_tap_create`?

**Comment by yogk** [comment]
@frederikvs : thanks.
No particular reason that i did not use pico_tap_create(),  its just that I started to use PicoTCP and not sure how its done , however now coming to your 2 solutions:

1.) use pico_tap_create() created by picotcp and add it to Linux bridge. How can this be done ? as pico_tap_create() I believe will create a tap device inside the picotcp which runs as an app. So how can linux command line have access to this tap device created by picotcp so that it can be added to the bridge along with eth0. Is there any way to do this ? Please let me know some info.

2.) creating a persistent tap device on linux itself using the commands 
sudo tunctl -u <username> 
sudo ifconfig tap0 192.168.5.5
After adding this tap0 to the bridge, how can we use pico_tap_create() to open this tap device (tap0) created from linux cmd line ? as in linux the tap device is accessible as char dev from /dev/net/tun. So can I pass this pico_tap_create("/dev/net/tun") from picoTCP to access it ? Or how is this done ?

I want to try both, so please let me know some details if possible.

Thanks in advance,
yk.
