### ISSUE TITLE
RAW_SOCKET pendant?

### ISSUE THREAD

**Issue by sknopp** [tass-belgium/picotcp#498]
Hi there,

I want to track all of the stacks traffic on the transport layer. By that I mean especially also single faulty FIN/RST/ACK packets arriving without any connection context. In Linux i would try to use _RAW_SOCKET_ for that. Is there any chance to achieve this with picoTCP too?

I digged a bit into the code and found the [`pico_tcp_input()`-function](https://github.com/tass-belgium/picotcp/blob/master/modules/pico_tcp.c#L2817). Would i need to manually customize this function to get those _pico_frames_ before they were dropped or are there any api functions i've missed?

Thanks!

**Comment by danielinux** [comment]
Hello @sknopp 
For this purpose, I'd recommend to modify your driver to create a copy of the sent/received packets, in the implementation of `your_pico_device->send()` and `your_pico_device.poll()`. You could for example  add an additional function to the driver, that can register a callback to receive a copy of either or both packets when they pass through it. Viceversa, you can inject forged packets by simply calling `pico_stack_recv()`. That should give you approximately the same range of functionalities as libpcap on a linux box. Check the [Example driver](https://github.com/tass-belgium/picotcp/wiki/Example-device-driver) page on the wiki for the explaination of `send()` and `pull()`.

If instead IP-level and ICMP-level sockets are actually what you are looking for, consider that 
some time ago we had started integrating raw socket on [frosted OS](https://gitlab.com/insane-adding-machines/frosted), and so we have added raw IP socket support on this (GPL only) [fork on gitlab](https://gitlab.com/insane-adding-machines/picotcp). 

IPv4 socket API is at https://gitlab.com/insane-adding-machines/picotcp/blob/master/modules/pico_ipv4.h#L115

**Comment by sknopp** [comment]
thank you! I will have a look into that!
